### model
model_name_or_path: /home/keruihuang/models/DeepSeek-R1-Distill-Qwen-7B

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: /home/keruihuang/LLaMA-Factory/examples/deepspeed/ds_z2_config.json
# 移除 finetuning_type 和所有 lora 相关配置

### dataset
dataset: dataset-5
template: deepseek3
cutoff_len: 2048
max_samples: 10000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: /home/keruihuang/models/DeepSeek-R1-Distill-Qwen-7B/sft_5
logging_steps: 10
save_steps: 300
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
optim: adamw_torch
learning_rate: 1.0e-5  # 全量微调通常使用更小的学习率
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
gradient_checkpointing: true  # 添加梯度检查点以节省显存

### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 50